
variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
- build
- test


GNU build:
  image: registry.git.rwth-aachen.de/luechow-group/inpsights/gnu:7.3.0
  stage: build
  before_script:
  - export CC=/usr/bin/gcc
  - export CXX=/usr/bin/g++
  script:
  - mkdir -p cmake-build-debug-gnu
  - cd cmake-build-debug-gnu
  - cmake .. -DCMAKE_BUILD_TYPE=DEBUG -DBUILD_GUI=OFF
  - cmake --build . --target inPsightsTests -- -j2
  cache:
    key: "$CI_COMMIT_REF_SLUG-GNU"
    paths:
    - cmake-build-debug-gnu/
    policy: pull-push

Intel build:
  image: registry.git.rwth-aachen.de/luechow-group/inpsights/intel:19.0.1.144
  stage: build
  before_script:
  - source /opt/intel/parallel_studio_xe_2019/psxevars.sh intel64
  - export CC=/opt/intel/bin/icc
  - export CXX=/opt/intel/bin/icpc
  - export MKLROOT=/opt/intel/mkl
  script:
  - mkdir -p cmake-build-debug-intel
  - cd cmake-build-debug-intel
  - cmake .. -DCMAKE_BUILD_TYPE=DEBUG -DBUILD_GUI=OFF
  - cmake --build . --target inPsightsTests -- -j2
  cache:
    key: "$CI_COMMIT_REF_SLUG-Intel"
    paths:
    - cmake-build-debug-intel/
    policy: pull-push

GNU test:
  image: registry.git.rwth-aachen.de/luechow-group/inpsights/gnu:7.3.0
  stage: test
  cache:
    key: "$CI_COMMIT_REF_SLUG-GNU"
    paths:
    - cmake-build-debug-gnu/
    policy: pull

  script:
  - cd cmake-build-debug-gnu
  - ctest -LE "(GUI)" -E "(example|spdlog-utests)" --output-on-failure -j4
  dependencies:
  - GNU build

Intel test:
  image: registry.git.rwth-aachen.de/luechow-group/inpsights/intel:19.0.1.144
  stage: test
  cache:
    key: "$CI_COMMIT_REF_SLUG-Intel"
    paths:
    - cmake-build-debug-intel/
    policy: pull

  before_script:
  - source /opt/intel/parallel_studio_xe_2019/psxevars.sh intel64
  script:
  - cd cmake-build-debug-intel
  - ctest -LE "(GUI|MaximaProcessing)" -E "(example|spdlog-utests)" --output-on-failure -j4
  dependencies:
  - Intel build

