
image: registry.git.rwth-aachen.de/luechow-group/amolqcpp:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - test

before_script:
  - export CC=/usr/bin/gcc
  - export CXX=/usr/bin/g++
  - export FC=/usr/bin/gfortran
  - export MATHLIBS=/usr/lib

BaseLib:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ..
    - cmake --build . --target BaseLibTests.exe -- -j2

BaseLibTests:
  stage: test
  script:
    - ./build/src/BaseLib/tests/BaseLibTests.exe
  #artifacts:
  #  paths:
  #  - build
