
image: registry.git.rwth-aachen.de/luechow-group/amolqcpp:combined

variables:
  GIT_SUBMODULE_STRATEGY: recursive

GNU tests:
  before_script:
  - export CC=/usr/bin/gcc
  - export CXX=/usr/bin/g++
  - export FC=/usr/bin/gfortran
  - export AMOLQC=/builds/luechow-group/Amolqcpp/src/AmolqcInterface/amolqc
  script:
  - mkdir -p cmake-build-debug-gnu
  - cd cmake-build-debug-gnu
  - cmake .. -DCMAKE_BUILD_TYPE=DEBUG -DBUILD_GUI=OFF
  - cmake --build . --target AmolqcppTests --
  - ctest -LE "(amolqc|GUI|cppoptlib)" -E "(example|spdlog-utests)" --output-on-failure
  cache:
    key: "$CI_COMMIT_REF_SLUG" # enable per-branch caching
    paths:
    - cmake-build-debug-gnu/

Intel tests:
  before_script:
  - export CC=/opt/intel/bin/icc
  - export CXX=/opt/intel/bin/icpc
  - export FC=/opt/intel/bin/ifort
  - export MKLROOT=/opt/intel/mkl
  - export AMOLQC=/builds/luechow-group/Amolqcpp/src/AmolqcInterface/amolqc
  script:
  - mkdir -p cmake-build-debug-intel
  - cd cmake-build-debug-intel
  - cmake .. -DCMAKE_BUILD_TYPE=DEBUG -DBUILD_GUI=OFF
  - cmake --build . --target AmolqcppTests --
  - ctest -LE "(amolqc|GUI|cppoptlib)" -E "(example|spdlog-utests)" --output-on-failure
  cache:
    key: "$CI_COMMIT_REF_SLUG" # enable per-branch caching
    paths:
    - cmake-build-debug-intel/
    