
image: registry.git.rwth-aachen.de/luechow-group/amolqcpp:latest

build:
  stage: build

  variables:
    GIT_SUBMODULE_STRATEGY: recursive

  before_script:
  - export CC=/usr/bin/gcc
  - export CXX=/usr/bin/g++
  - export FC=/usr/bin/gfortran

  script:
    - mkdir -p build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=DEBUG -DBUILD_GUI=OFF
    - cmake --build . --target AmolqcppTests -- -j 2

  cache:
    key: "$CI_COMMIT_REF_SLUG" # enable per-branch caching
    paths:
    - build/

test:
  stage: test
  dependencies:
  - build

  script:
    - export AMOLQC=/builds/luechow-group/Amolqcpp/src/AmolqcInterface/amolqc
    - ctest -LE "(amolqc|GUI|cppoptlib)" -E "(example|spdlog-utests)" --verbose
