
image: registry.git.rwth-aachen.de/luechow-group/amolqcpp:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

AllTests:
  before_script:
  - export CC=/usr/bin/gcc
  - export CXX=/usr/bin/g++
  - export FC=/usr/bin/gfortran
  - export MATHLIBS=/usr/lib/x86_64-linux-gnu
  - export AMOLQC=/builds/luechow-group/Amolqcpp/src/AmolqcInterface/amolqc

  script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=DEBUG -DBUILD_GUI=OFF
    - cmake --build . --target AmolqcppTests -- -j 2
    - ctest -LE "(amolqc|GUI)" -E "(example|spdlog-utests)"
